### ISSUE TITLE
[Bug]: not able to add bot to discord server

### ISSUE THREAD

**Issue by Shaiktit** [MonarchDevelopment/SquireBot#80]
## What went wrong:
Not able to add into server

![image](https://github.com/SquireTournamentServices/SquireBot/assets/121429408/509dd309-bb8a-460c-a48a-fc289eea4d05)

**Comment by TylerBloom** [comment]
Yes, this is a known issue. The issue here is that SquireBot is not verified by Discord, so it can only join a limited number of servers. You should be able to add the "Prototype" version (same code, different bot account) to your server. Link below:

https://discord.com/api/oauth2/authorize?client_id=784929803018829864&permissions=8&scope=bot
